---
title: "WUF Data Processing"
output: html_document
date: "2022-09-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Load WUF Data

Composite Nutrient data provided in excel with site description in separate tab

```{r data load}
setwd("~/WUF_Data/WUF_Data_processing")
library(readxl)
Compiled_Data <- read_excel("Compiled Data.xlsx", 
    col_types = c("text", "text", "text", 
        "date", "numeric", "skip", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))
View(Compiled_Data)
```

## Including Plots

You can also embed plots, for example:

```{r}
ggplot(Compiled_Data, aes(x=Site_code, y=Orthophosphate)) +
    geom_boxplot(aes(fill=Site_code)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


ggplot(Compiled_Data, aes(x=Date_Sampled, y=Orthophosphate)) +
    geom_line() +
    geom_point() +
    facet_wrap(~Site_code, ncol = 4) +
    theme_linedraw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

ggplot(Compiled_Data, aes(x=Site_code, y=AHP)) + geom_boxplot(aes(fill=Site_code)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(Compiled_Data, aes(x=Date_Sampled, y=AHP)) + geom_line() +
  geom_point() + facet_wrap(~Site_code, ncol = 4) + theme_linedraw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(Compiled_Data, aes(x=Site_code, y=Organic_Phosphorus)) + geom_boxplot(aes(fill=Site_code)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(Compiled_Data, aes(x=Date_Sampled, y=Organic_Phosphorus)) + geom_line() +
  geom_point() + facet_wrap(~Site_code, ncol = 4) + theme_linedraw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 

ggplot(Compiled_Data, aes(x=Site_code, y=Total_Phosphorus)) + geom_boxplot(aes(fill=Site_code)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggplot(Compiled_Data, aes(x=Date_Sampled, y=Total_Phosphorus)) + geom_line() +
  geom_point() + facet_wrap(~Site_code, ncol = 4) + theme_linedraw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
